name: Deploy Next.js estático
on:
  push:
    branches: ["main"] # Ou o nome da sua branch principal
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - name: Build project
        run: |
          echo "Iniciando build..."
          pnpm build
          echo "Build finalizado com sucesso."
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4